# src/etl/schema.py

# Diccionario de claves ENT a nombre de entidad
ENTIDADES = {
    1: "AGUASCALIENTES", 2: "BAJA CALIFORNIA", 3: "BAJA CALIFORNIA SUR", 4: "CAMPECHE",
    5: "COAHUILA", 6: "COLIMA", 7: "CHIAPAS", 8: "CHIHUAHUA", 9: "CIUDAD DE MEXICO",
    10: "DURANGO", 11: "GUANAJUATO", 12: "GUERRERO", 13: "HIDALGO", 14: "JALISCO",
    15: "ESTADO DE MEXICO", 16: "MICHOACAN", 17: "MORELOS", 18: "NAYARIT", 19: "NUEVO LEON",
    20: "OAXACA", 21: "PUEBLA", 22: "QUERETARO", 23: "QUINTANA ROO", 24: "SAN LUIS POTOSI",
    25: "SINALOA", 26: "SONORA", 27: "TABASCO", 28: "TAMAULIPAS", 29: "TLAXCALA",
    30: "VERACRUZ", 31: "YUCATAN", 32: "ZACATECAS"
}

# Diccionario de columnas finales para el consolidado
columnas_finales_planea = [
    "ANIO_EVALUACION", "ENT", "ENTIDAD", "CLAVE_ESCUELA", "NOMBRE_ESCUELA", "TURNO",
    "MUNICIPIO", "LOCALIDAD", "TIPO_ESCUELA", "GRADO_EVALUADO", "GRADO_MARGINACION",
    "ALUMNOS_PROGRAMADOS", "ALUMNOS_EVALUADOS_LENGUAJE", "ALUMNOS_EVALUADOS_MATEMATICAS",
    "PORCENTAJE_EVALUADOS_LENGUAJE", "PORCENTAJE_EVALUADOS_MATEMATICAS",
    "REPRESENTATIVIDAD_LENGUAJE", "REPRESENTATIVIDAD_MATEMATICAS",
    "CONFIABILIDAD_LENGUAJE", "CONFIABILIDAD_MATEMATICAS", "ESCUELAS_PARECIDAS",
    "LENGUAJE_CANTIDAD_I", "LENGUAJE_CANTIDAD_II", "LENGUAJE_CANTIDAD_III", "LENGUAJE_CANTIDAD_IV",
    "LENGUAJE_PCT_I", "LENGUAJE_PCT_II", "LENGUAJE_PCT_III", "LENGUAJE_PCT_IV",
    "LENGUAJE_PARECIDAS_PCT_I", "LENGUAJE_PARECIDAS_PCT_II", "LENGUAJE_PARECIDAS_PCT_III", "LENGUAJE_PARECIDAS_PCT_IV",
    "LENGUAJE_NACIONAL_PCT_I", "LENGUAJE_NACIONAL_PCT_II", "LENGUAJE_NACIONAL_PCT_III", "LENGUAJE_NACIONAL_PCT_IV",
    "MATEMATICAS_CANTIDAD_I", "MATEMATICAS_CANTIDAD_II", "MATEMATICAS_CANTIDAD_III", "MATEMATICAS_CANTIDAD_IV",
    "MATEMATICAS_PCT_I", "MATEMATICAS_PCT_II", "MATEMATICAS_PCT_III", "MATEMATICAS_PCT_IV",
    "MATEMATICAS_PARECIDAS_PCT_I", "MATEMATICAS_PARECIDAS_PCT_II", "MATEMATICAS_PARECIDAS_PCT_III", "MATEMATICAS_PARECIDAS_PCT_IV",
    "MATEMATICAS_NACIONAL_PCT_I", "MATEMATICAS_NACIONAL_PCT_II", "MATEMATICAS_NACIONAL_PCT_III", "MATEMATICAS_NACIONAL_PCT_IV",
    "PERCEPCION_BIENESTAR_CANTIDAD_1", "PERCEPCION_BIENESTAR_CANTIDAD_2", "PERCEPCION_BIENESTAR_CANTIDAD_3", "PERCEPCION_BIENESTAR_CANTIDAD_4",
    "PERCEPCION_BIENESTAR_PCT_1", "PERCEPCION_BIENESTAR_PCT_2", "PERCEPCION_BIENESTAR_PCT_3", "PERCEPCION_BIENESTAR_PCT_4",
    "PERCEPCION_BIENESTAR_PARECIDAS_PCT_1", "PERCEPCION_BIENESTAR_PARECIDAS_PCT_2", "PERCEPCION_BIENESTAR_PARECIDAS_PCT_3", "PERCEPCION_BIENESTAR_PARECIDAS_PCT_4",
    "PERCEPCION_BIENESTAR_NACIONAL_PCT_1", "PERCEPCION_BIENESTAR_NACIONAL_PCT_2", "PERCEPCION_BIENESTAR_NACIONAL_PCT_3", "PERCEPCION_BIENESTAR_NACIONAL_PCT_4",
    "MARGINACION_PARECIDAS_ALTO", "MARGINACION_PARECIDAS_MEDIO", "MARGINACION_PARECIDAS_BAJO",
    "MARGINACION_NACIONAL_ALTO", "MARGINACION_NACIONAL_MEDIO", "MARGINACION_NACIONAL_BAJO",
    "ARCHIVO_ORIGEN"
]


